Algoritmo "somadosinteiros"

Var
   contador, soma: inteiro

Inicio
   //Passo para criar a estrutura de repetição do contador de 100 a 1500
   contador := 1
   soma := 0
   Enquanto (contador >= 1) e (contador <= 10) Faca
         contador := contador + 1
         soma := soma + contador //Expressão para somar dos inteiros
   Fimenquanto
   Escreva ("A soma dos inteiros é:", soma) // Passo para exibir o resultado
Fimalgoritmo
